log_level: INFO # log-level - valid-values: ALL MARK TRACE DEBUG INFO WARN ERROR FATAL OFF
behaviour:
  show_on_load: true # show the first slide when loading - valid-values: true false
  bible_citation_style: 1. Moses 1,2-4.6; 7 # Citation-stype for bible passages. Syntax: Citation for "1. Moses" with chapter 1, verses 2-4 and 6 and chapter 7
path: # path to the different files
  playlist: /12_Abläufe/ # song-files
  song: /80_Songs/Lieder # pdf-files
  psalm: /80_Songs/Psalme # psalm-files
  pdf: /60_PDF/ # playlist-files
  bible: files/Bible/Lutherbibel.json # used bible
casparcg:
  transition_length: 12 # transition-length in frames
  connections: # individual CasparCG-connections
    - host: 127.0.0.1
      port: 5250
      channel: 1
      layers:
        media: 20 # used for media-playback - Can be removed to don't show media
        template: 21 # used for templates and song-/psalm-/countdown-text
      path: casparcg_v2.4.0 # - optional path to CasparCG-directory to auto-start at launch
      # stageview: true # optional - show song-chords and hide song-backgrounds
client_server:
  http:
    port: 8888 # port for the client-interface web-server
  websocket:
    port: 8765 # port for the websocket-communication between client and server (needs to be changed in client/assets/main-*.js - search for 'port:"')