title: JohnCG
description: Documentation for JohnCG
theme: just-the-docs

baseurl: "/johncg"

timezone: Europe/Berlin

url: https://johannesbuehl.github.io/johncg

# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  setup:
    output: true
  usage:
    output: true
  files_and_protocol:
    output: true

just_the_docs:
  collections:
    setup:
      name: Setup
    usage:
      name: Usage
    files_and_protocol:
      name: Files and Protocol
    

favicon_ico: favicon.ico
search_enabled: true

aux_links:
  GitHub Repository: https://github.com/johannesbuehl/JohnCG

footer_content: "<a href=\"/johncg/impressum\">Impressum</a> | <a href=\"/johncg/datenschutz\">Datenschutz</a>"
